name: altruist_secure_flutter
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+50


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+4
  path: ^1.6.4
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter_bloc: ^2.1.1
  crypto: ^2.1.3
  modal_progress_hud: ^0.1.3
  json_annotation: ^3.0.1
  intro_slider: 2.2.9
  flutter_downloader: 1.4.4
  flutter_email_sender: 3.0.1





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  permission: ^0.1.1
  dio: 3.0.0
  rxdart:  ^0.22.0
  http: ^0.12.0
  image_picker: ^0.6.1+4
  video_player: 0.10.8+1
  sim_info: ^0.1.1
  permission_handler: ^3.2.2
  progress_dialog: ^1.2.1
  vibration: ^1.2.4
  torch: ^0.1.1
  toast: ^0.1.5
  shared_preferences: 0.5.3+1
  flutter_easyloading: ^1.0.1
  firebase_core: 0.4.0
  firebase_crashlytics: ^0.1.3+3
  firebase_auth: 0.15.3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  rflutter_alert: ^1.0.3
  month_picker_dialog: ^0.3.0
  device_info: ^0.4.1+5
  email_validator: ^1.0.0
  date_format: ^1.0.8
  webview_flutter: 0.3.22+1
  sim_service: ^0.1.0
  imei_plugin: ^1.1.6
  simple_pdf_viewer: ^0.2.2
  package_info: ^0.4.0+17
  store_redirect: ^1.0.2
  devicelocale: ^0.2.3
  flutter_sim_country_code: ^0.0.3
  sweetalert: ^0.0.1
  path_provider: 1.5.1
  url_launcher: ^5.0.3
  screenshot: ^0.2.0
  image_gallery_saver: ^1.5.0
  need_resume: ^1.0.4
  connectivity: ^0.4.9+3

#  ussd_service: ^0.1.0+4
#  flutter_dialpad: ^1.0.0
 # get_version: 0.2.2

#  url_launcher: ^5.2.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true




  assets:
    - altruist_logo.png
    - call_back_request.png
    - help_phone.png
    - raise_a_claim.png
    - view_certificate.png
    - splash_screen.png
    - icons_upload_document.png
    - content_secure.jpg
    - moble_secure.jpg
    - plan_and_make_payment.jpg
    - bluetooth_blue.png
    - flash_blue.png
    - headphones_blue.png
    - display_test_blue.png
    - sim_card_blue.png
    - speaker_blue.png
    - mobile_phone_vibrating_blue.png
    - wifi_blue.png
    - camera_blue.png
    - bluetooth_grey.png
    - camera_grey.png
    - flash_grey.png
    - headphones_grey.png
    - sim_card_grey.png
    - speaker_grey.png
    - mobile_phone_vibrating_grey.png
    - wifi_grey.png
    - display_grey.png
    - tick.png
    - wrong.png
    - refresh.png
    - progresstrue.png
    - progressfalse.png
    - face_lock_grey.png
    - fingerprint_grey.png
    - profile_management.png
    - sansors_blue.png
    - sensors_grey.png
    - edit.png
    - altruist_secure_logo.png
    - splash_screen_altruist_secure.png
    - document.png
    - altruist_secure_t_c.html
    - splash_screen_noon_secure.png
    - noon_secure_logo.png
    - screen_glass_image.png
    - action_arrow.png
    - user_profile.png
    - process_flow.png
    - payment_status.png
    - splash_screen_airteltigo_secure.png
    - splash_screen_mansard_secure.png
    - partnered_logos.png
    - splash_screen_altruist_secure_ghana.jpg
    - powered_by_image.png



  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBoldItalic.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:





  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
