
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules:
  - trailing_whitespace
  - multiple_closures_trailing_closure
  - identifier_name
  - duplicate_enum_cases
  - no_extension_access_modifier
  - empty_count

line_length:
    warning: 170
    error: 400

variable_name:
    min_length: 2

type_name:
    max_length: 50

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_empty_lines: true
